name: 'Upload to Public Releases Repo'

on:
  workflow_run:
    workflows: ["publish"]
    types:
      - completed

jobs:
  upload-release-assets:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the public releases repo
        uses: actions/checkout@v4
        with:
          repository: your-username/your-releases-repo
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: main

      - name: Download the release assets from the source repo
        uses: actions/download-artifact@v2
        with:
          name: release-assets
          path: ./assets

      - name: Upload release to public repo
        run: |
          # Create a GitHub release in the public repo and upload the assets
          RELEASE_TAG="v$(date +'%Y%m%d%H%M%S')"  # or use version info from source repo
          gh release create $RELEASE_TAG ./assets/* --title "App v$RELEASE_TAG" --notes "Release Notes here"

      - name: Push changes to the public repo
        run: git push origin main
